name: Main Pipeline

on:
  push:

jobs:
  build:
    name: Build
    runs-on: org-self-hosted-ubuntu2204-x64-xsmall
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - uses: gradle/actions/setup-gradle@v3

      - run: ./gradlew check

      - run: ./gradlew publishToMavenLocal

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: "dump"
          path: "**/*.hprof"

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: "dump2"
          path: "/home/runner/.gradle/daemon/8.10-20240718001640+0000/daemon-*.out.log"

